
import { PlanetData } from './types';

// LRM = \u200E is used to ensure the minus sign stays on the left of the number in RTL text.
const LRM = '\u200E';

export const SUN: PlanetData = {
  id: 'sun',
  name: 'השמש',
  englishName: 'The Sun',
  distanceFromSun: '0 ק"מ (מרכז המערכת)',
  water: 'אין (חם מדי!)',
  atmosphere: 'פוטוספירה, כרומוספירה ועטרה',
  dayLength: '25-35 ימי כדור הארץ',
  yearLength: '230 מיליון שנים (סביב הגלקסיה)',
  type: 'כוכב',
  color: '#fbbf24',
  size: 40,
  orbitalSpeed: 0,
  realSize: '1,392,700 ק"מ',
  moonsCount: 0,
  humanReached: false,
  explorationTools: 'SOHO, Parker Solar Probe',
  temperature: `5,500 מעלות צלזיוס (על פני השטח), 15 מיליון מעלות (בליבה)`,
  imageUrl: 'https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e000790/GSFC_20171208_Archive_e000790~thumb.jpg',
  description: 'השמש היא הכוכב במרכז מערכת השמש שלנו. היא כדור פלזמה לוהט וענקי שמכיל 99.8% מכל המסה במערכת השמש כולה!'
};

export const PLANETS: PlanetData[] = [
  {
    id: 'mercury',
    name: 'כוכב חמה',
    englishName: 'Mercury',
    distanceFromSun: '58 מיליון ק"מ',
    water: 'אין מים נוזליים',
    atmosphere: 'דלילה מאוד: חמצן, נתרן ומימן.',
    dayLength: '59 ימי כדור הארץ',
    yearLength: '88 ימי כדור הארץ',
    type: 'ארצי',
    color: '#94a3b8',
    size: 6,
    orbitalSpeed: 3.5,
    realSize: '4,879 ק"מ',
    moonsCount: 0,
    humanReached: false,
    explorationTools: 'MESSENGER, BepiColombo',
    temperature: `מ-${LRM}-173 מעלות צלזיוס ועד 427 מעלות צלזיוס`,
    imageUrl: 'https://images-assets.nasa.gov/image/PIA15162/PIA15162~thumb.jpg',
    description: 'הוא כוכב הלכת הכי קרוב לשמש! בגלל שאין לו אטמוספירה שתשמור על החום, בלילה נורא קר וביום נורא חם.'
  },
  {
    id: 'venus',
    name: 'נוגה',
    englishName: 'Venus',
    distanceFromSun: '108 מיליון ק"מ',
    water: 'אין מים',
    atmosphere: 'סמיכה מאוד: פחמן דו-חמצני וחנקן.',
    dayLength: '243 ימי כדור הארץ',
    yearLength: '225 ימי כדור הארץ',
    type: 'ארצי',
    color: '#fbbf24',
    size: 10,
    orbitalSpeed: 2.8,
    realSize: '12,104 ק"מ',
    moonsCount: 0,
    humanReached: false,
    explorationTools: 'Venera, Magellan',
    temperature: '462 מעלות צלזיוס',
    imageUrl: 'https://images-assets.nasa.gov/image/PIA00271/PIA00271~thumb.jpg',
    description: 'נוגה הוא כוכב הלכת הכי חם במערכת השמש. יש לו עננים סמיכים שכולאים את החום כמו בחממה.'
  },
  {
    id: 'earth',
    name: 'כדור הארץ',
    englishName: 'Earth',
    distanceFromSun: '150 מיליון ק"מ',
    water: 'יש המון! (71%)',
    atmosphere: 'חנקן (78%) וחמצן (21%).',
    dayLength: '24 שעות',
    yearLength: '365 ימים',
    type: 'ארצי',
    color: '#3b82f6',
    size: 11,
    orbitalSpeed: 2.2,
    realSize: '12,742 ק"מ',
    moonsCount: 1,
    humanReached: true,
    explorationTools: 'לוויינים ותחנת החלל',
    temperature: `מ-${LRM}-88 מעלות צלזיוס ועד 58 מעלות צלזיוס`,
    imageUrl: 'https://images-assets.nasa.gov/image/PIA00122/PIA00122~thumb.jpg',
    description: 'הבית המקסים שלנו! זהו המקום היחיד ביקום שאנחנו יודעים בוודאות שיש בו חיים, צמחים וחיות.'
  },
  {
    id: 'mars',
    name: 'מאדים',
    englishName: 'Mars',
    distanceFromSun: '228 מיליון ק"מ',
    water: 'קרח בקטבים',
    atmosphere: 'דלילה: פחמן דו-חמצני וארגון.',
    dayLength: '24.6 שעות',
    yearLength: '687 ימים',
    type: 'ארצי',
    color: '#ef4444',
    size: 8,
    orbitalSpeed: 1.8,
    realSize: '6,779 ק"מ',
    moonsCount: 2,
    humanReached: false,
    explorationTools: 'רוברים כמו Perseverance',
    temperature: `מ-${LRM}-153 מעלות צלזיוס ועד 20 מעלות צלזיוס`,
    imageUrl: 'https://images-assets.nasa.gov/image/PIA02653/PIA02653~thumb.jpg',
    description: 'הוא נקרא "כוכב הלכת האדום" כי יש עליו המון חלודה. בעתיד אולי בני אדם יגורו שם!'
  },
  {
    id: 'ceres',
    name: 'צרס',
    englishName: 'Ceres',
    distanceFromSun: '414 מיליון ק"מ',
    water: 'שכבת קרח פנימית',
    atmosphere: 'כמעט ואין: אדי מים.',
    dayLength: '9 שעות',
    yearLength: '4.6 שנים',
    type: 'ננסי',
    color: '#a1a1aa',
    size: 3,
    orbitalSpeed: 1.4,
    realSize: '940 ק"מ',
    moonsCount: 0,
    humanReached: false,
    explorationTools: 'Dawn Mission',
    temperature: `${LRM}-105 מעלות צלזיוס`,
    imageUrl: 'https://images-assets.nasa.gov/image/PIA18920/PIA18920~thumb.jpg',
    description: 'זהו כוכב הלכת הננסי הכי קרוב אלינו. הוא נמצא בחגורת האסטרואידים שבין מאדים לצדק.'
  },
  {
    id: 'jupiter',
    name: 'צדק',
    englishName: 'Jupiter',
    distanceFromSun: '778 מיליון ק"מ',
    water: 'מעט אדים בעננים',
    atmosphere: 'ענקית: מימן והליום.',
    dayLength: '9.9 שעות',
    yearLength: '11.8 שנים',
    type: 'גזי',
    color: '#d97706',
    size: 24,
    orbitalSpeed: 1.1,
    realSize: '139,820 ק"מ',
    moonsCount: 95,
    moonsDetails: 'איו, אירופה, גנימד וקליסטו',
    humanReached: false,
    explorationTools: 'Juno, Galileo',
    temperature: `${LRM}-110 מעלות צלזיוס`,
    imageUrl: 'https://images-assets.nasa.gov/image/PIA04866/PIA04866~thumb.jpg',
    description: 'הוא הכי גדול במערכת השמש! יש עליו סערה ענקית בצורת עין אדומה שקיימת כבר מאות שנים.'
  },
  {
    id: 'saturn',
    name: 'שבתאי',
    englishName: 'Saturn',
    distanceFromSun: '1.4 מיליארד ק"מ',
    water: 'קרח בטבעות',
    atmosphere: 'גזית: מימן והליום.',
    dayLength: '10.7 שעות',
    yearLength: '29.4 שנים',
    type: 'גזי',
    color: '#f59e0b',
    size: 20,
    orbitalSpeed: 0.8,
    realSize: '116,460 ק"מ',
    moonsCount: 146,
    moonsDetails: 'טיטאן (הירח המפורסם)',
    humanReached: false,
    explorationTools: 'Cassini, Voyager',
    temperature: `${LRM}-140 מעלות צלזיוס`,
    imageUrl: 'https://images-assets.nasa.gov/image/PIA01364/PIA01364~thumb.jpg',
    description: 'שבתאי מפורסם בטבעות המדהימות שלו, שעשויות ממיליוני חתיכות קרח ואבק.'
  },
  {
    id: 'uranus',
    name: 'אורנוס',
    englishName: 'Uranus',
    distanceFromSun: '2.9 מיליארד ק"מ',
    water: 'קרח וגז',
    atmosphere: 'קפואה: מימן, הליום ומתאן.',
    dayLength: '17.2 שעות',
    yearLength: '84 שנים',
    type: 'גזי',
    color: '#22d3ee',
    size: 16,
    orbitalSpeed: 0.5,
    realSize: '50,724 ק"מ',
    moonsCount: 28,
    humanReached: false,
    explorationTools: 'Voyager 2, JWST',
    temperature: `${LRM}-195 מעלות צלזיוס`,
    imageUrl: 'https://images-assets.nasa.gov/image/PIA26221/PIA26221~thumb.jpg',
    description: 'אורנוס הוא ענק קרח כחול ומיוחד. בתמונה זו מטלסקופ החלל ג\'יימס ווב (JWST) ניתן לראות בבירור את הטבעות המרהיבות שלו ואת האטמוספירה הדינמית שלו.'
  },
  {
    id: 'neptune',
    name: 'נפטון',
    englishName: 'Neptune',
    distanceFromSun: '4.5 מיליארד ק"מ',
    water: 'קרח עמוק',
    atmosphere: 'סוערת: מימן, הליום ומתאן.',
    dayLength: '16.1 שעות',
    yearLength: '165 שנים',
    type: 'גזי',
    color: '#6366f1',
    size: 15,
    orbitalSpeed: 0.4,
    realSize: '49,244 ק"מ',
    moonsCount: 14,
    humanReached: false,
    explorationTools: 'Voyager 2',
    temperature: `${LRM}-201 מעלות צלזיוס`,
    imageUrl: 'https://images-assets.nasa.gov/image/PIA01492/PIA01492~thumb.jpg',
    description: 'זהו כוכב הלכת הכי רחוק מהשמש. יש בו רוחות כל כך חזקות שהן מהירות יותר ממטוס סילון!'
  },
  {
    id: 'pluto',
    name: 'פלוטו',
    englishName: 'Pluto',
    distanceFromSun: '5.9 מיליארד ק"מ',
    water: 'קרח חנקן ומים',
    atmosphere: 'דלילה: חנקן ומתאן.',
    dayLength: '153 שעות',
    yearLength: '248 שנים',
    type: 'ננסי',
    color: '#9ca3af',
    size: 4,
    orbitalSpeed: 0.3,
    realSize: '2,376 ק"מ',
    moonsCount: 5,
    humanReached: false,
    explorationTools: 'New Horizons',
    temperature: `${LRM}-225 מעלות צלזיוס`,
    imageUrl: 'https://images-assets.nasa.gov/image/PIA19952/PIA19952~thumb.jpg',
    description: 'פעם הוא נחשב לכוכב לכת רגיל, אבל היום הוא כוכב לכת ננסי. הוא קטן יותר מהירח שלנו!'
  },
  {
    id: 'charon',
    name: 'כארון',
    englishName: 'Charon',
    distanceFromSun: '5.9 מיליארד ק"מ',
    water: 'קרח מים',
    atmosphere: 'אין אטמוספירה.',
    dayLength: '6.4 ימים',
    yearLength: '248 שנים',
    type: 'ננסי',
    color: '#71717a',
    size: 3,
    orbitalSpeed: 0.3,
    realSize: '1,212 ק"מ',
    moonsCount: 0,
    humanReached: false,
    explorationTools: 'New Horizons',
    temperature: `${LRM}-220 מעלות צלזיוס`,
    imageUrl: 'https://images-assets.nasa.gov/image/PIA19968/PIA19968~thumb.jpg',
    description: 'זהו הירח הגדול של פלוטו. הוא כל כך גדול יחסית אליו שהם נראים כמו שני חברים שרוקדים יחד בחלל.'
  },
  {
    id: 'eris',
    name: 'אריס',
    englishName: 'Eris',
    distanceFromSun: '10 מיליארד ק"מ',
    water: 'קרח מתאן',
    atmosphere: 'דלילה וקפואה: חנקן.',
    dayLength: '25.9 שעות',
    yearLength: '557 שנים',
    type: 'ננסי',
    color: '#e2e8f0',
    size: 4,
    orbitalSpeed: 0.2,
    realSize: '2,326 ק"מ',
    moonsCount: 1,
    humanReached: false,
    explorationTools: 'Hubble, Keck',
    temperature: `${LRM}-231 מעלות צלזיוס`,
    imageUrl: 'https://images-assets.nasa.gov/image/PIA03034/PIA03034~thumb.jpg',
    description: 'אריס נמצא רחוק רחוק בקצה מערכת השמש. הוא כל כך קר שגם הגזים שלו הופכים לקרח שמכסה אותו.'
  }
];
